### PR TITLE
Export ipcInterface, 'use strict', initialize vars before use

### PR DESCRIPTION
**Pull request by jeffnappi**
Hi guys, thanks for putting this together. I was working with @xnappo on using `node-mpv` for the Emby Theater Linux project and came across a few small issues.

Merry Xmas :evergreen_tree: :santa:

### CODE REVIEW

**Comment by j-holub** [comment]
Thank you very much. I'm coming from a C++/Java/Haskell/ strict type system language background, that's why I'm all for this.
I briefly read about the `use strict` feature and it seems to be pretty much backwards compatible. Since this is not meant to be run inside a browser it should be safe anyways.

Merry Christmas  :)

**Comment by j-holub** [comment]
Excited to see your Emby Theater Project by the way :)

**Comment by jeffnappi** [comment]
Thank you, and happy new year! The emby theater for Linux project is here: https://github.com/MediaBrowser/emby-theater-linux

work in progress :)

**Comment by xnappo** [comment]
Here is the user forum post:
https://emby.media/community/index.php?/topic/42868-emby-theater-for-linux/

Work will be slow as (1) I am new to JS and (2) I have several other projects :)  node-mpv definitely made getting to the point we are at easier though - thanks!

**Comment by j-holub** [comment]
Looks great!

I was new to JS as well, so I feel you. And yes, the time for all the projects...
I originally wrote Node-MPV for my MusicServer project which is written in Meteor (based on NodeJs), if you wanna take a look at that it can be found here: https://github.com/00SteinsGate00/MusicServer

Glad to hear that Node-MPV has made your life easier. I hope you won't run into any severe bugs that'll waste your time. Thank you for using it :)

**Pull request merged**
