### PR TITLE
- On startup, added stderr + pipe check.

### PR DESCRIPTION
**Pull request by twilson90**
- On startup, added stderr + pipe check.
- Added statuschange_single emit for tracking a single property change.
- Added goto() for changing playlist-pos, similar to prev() and next(), checks if newPosition is in playlist range, waits for item to load before resolving.

### CODE REVIEW

**Comment by j-holub** [comment]
Those are two very different things to put into one single commit.

Just emitting the message with `this.emit('statuschange_single', message)` will send the whole message in the form of
```JavaScript
{
   event: 'property-change',
   id: 9, name: 'playlist-count',
   data: 1
}
```
which is pretty raw. If every single event will be `property-change`, there's no reason to output it. It doesn't really match the formatting of the rest of the library. But you have a very good idea there in my opinion. It might be better to swap this huge *statuschange* object for many single statuschange messages instead, thank you. We can discuss this further to see how we can implement this in a nice way, shouldn't be too much of a hassle. It's just difficult not to break the API for people already using it.

As for the `stderr` thing, I'm not really sure yet, as discussed in #63 .

For the future, it would be better to separate commits or even pull requests logically, because these are two very different things in one commit and in one pull request. For example, I wanted to merge the `statusevent_single` part but not the other part or vice versa, it's not really possible.

Thanks for taking the time to help this library to improve :)

**Comment by twilson90** [comment]
Sorry about that, I should have taken the time to break it up into separate commits / pull requests.

**Comment by twilson90** [comment]
Also, regarding the emitting of 'statuschange_single', I'll just add that it is a very useful thing to have if you want to efficiently communicate mpv changes via a websocket (as I am).
Just re-sending the decoded ipc message was a bit ghetto, I'll admit... 1 line though  :)

**Comment by j-holub** [comment]
Yeah you're right, that stderr can have multiple listeners, my bad. I would like to merge that part.

As for the `statuschange_single` thing, I love the idea, I'm just not yet a friend of the implementation and I don't know if I like the naming. It feels most natural to me, to replace the old `statuschange` behaviour where it outputs the complete object every time. The good thing about doing a V2 is, that we can pretty much break the API.

I just saw your `goTo()` function, great addition, like it.

If you could kinda separate the commits and mabye split it up on multiple PRs, that'd be great. You don't have to close/delete this one, you can just change it. Then I can merge it.

**Comment by j-holub** [comment]
Thanks for the changes. I still don't see why there's a need to check for `file-loaded` on `start()`, which file are we waiting for when we start **mpv** in idle mode?

And these are still two things, that do not belong into a single commit. If I/we ever have to revert t this commit because of some bug in the `start()` method, it will delete the `goTo()` method as well.

**Comment by twilson90** [comment]
> If you could kinda separate the commits and mabye split it up on multiple PRs, that'd be great. You don't have to close/delete this one, you can just change it. Then I can merge it.

Will do,

> Thanks for the changes. I still don't see why there's a need to check for `file-loaded` on `start()`, which file are we waiting for when we start **mpv** in idle mode?

I'll try to explain this better in the issue thread:
https://github.com/j-holub/Node-MPV/issues/63

**Comment by twilson90** [comment]
Added the fixes + improvements as separate pull requests.
Am bit of a git noob so I hope it's as you requested.

**Comment by j-holub** [comment]
I close this one because you filed some new sperate pull requests and I don't think this one is still needed

**Pull request closed without merging**
