### PR TITLE
replace 'promise' module by native node Promise()

### PR DESCRIPTION
**Pull request by vankasteelj**

### CODE REVIEW

**Comment by vankasteelj** [comment]
it was actually really simple as you didn't use anything else than `new Promise((resolve, reject) => {})`

**Comment by vankasteelj** [comment]
there are still lots of .bind(this) you could probably remove as you use arrow functions, but I don't know if that was intentionnal (not the same this)

**Comment by j-holub** [comment]
Yep you're right about the `bind` thing. When I wrote the module I didn't know of the arrow functions yet. In Ver2 I should've removed most of the `bind` already and replaced it with the arrow functions.

**Comment by vankasteelj** [comment]
take on those `var` while you're at it 👍

**Comment by j-holub** [comment]
Yep had that in my mind for a long time now, too ;) Already removed some on go

**Pull request merged**
