### PR TITLE
TypeScript binding

### LINKED ISSUE #73: Typescript
We talked about this a long time ago, and I had volunteered to help a bit with this particular issue, if you'd like.

I did look into it many months ago, and my main issue was that this would involve a more or less complete rewrite of the code to be typescript and modern JS-compliant. 

It oculd take some time, but I do happen to have some free time now that we reached a big milestone with Karaoke Mugen (now powered by Electron)

If you're still interested, I can start working on it, but it'll be a all-or-nothing approach : as we can't just have parts in typescript and other parts in plain JS.

If you'd like to talk more about this via Discord, add AxelTerizaki#0001 there.

### PR DESCRIPTION
**Pull request by leonekmi**
Closes #73 

This type declaration contains full documentation based on comments in your original code.

### CODE REVIEW

**Comment by j-holub** [comment]
Hey there,

thanks for the hard work! I'm starting my full time job tomorrow so I still have some stuff to take care of today, but I'll try to look into it within the next days. Thank you very much : )

**Comment by j-holub** [comment]
In `index.d.ts` line **17** you wrote `auto_restart?: true`, I'm not super familiar with TypeScript, does that mean true is the default value or does that mean you can only use true for that and not false?

**Comment by leonekmi** [comment]
You're right, it's my fault, it should be `boolean` like the others.

**Comment by j-holub** [comment]
Sorry for the late reply, not used to this full time job thing yet. `times` for both `loop()` and `loopPlaylist()` has to be optional, I think that's `times?`, right? I can change it myself if you want to.

Other than that, I think this PR can be merged. Thanks a lot for the work, this is a really awesome addition to the project in my opinion.

**Comment by leonekmi** [comment]
I fixed declarations for loop and loopPlaylist, i didn't see the cycle property if parameter is not specified.

**Comment by j-holub** [comment]
It's in the readme but I agree, that it is easy to miss, I should probably rephrase that more clearly. If you do no pass any argument, it toggles between looping and not looping.

**Pull request merged**
